/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import datautils.userData;
import datautils.classData;
/**
 *
 * @author Shivatej Patil
 */
public class home extends javax.swing.JFrame {
    private Connection c;
    private userData u;
    private classData[] classesData;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }
    public home(Connection c, userData u) {
        initComponents();
        this.c = c;
        this.u = u;
        this.classesData = new classData[3];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        welcomeMsg = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cls1 = new javax.swing.JButton();
        cls2 = new javax.swing.JButton();
        cls3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Create Class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        welcomeMsg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcomeMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeMsg.setText("Home");

        jButton2.setText("Join Class");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cls1.setText("class_1");
        cls1.setVisible(false);
        cls1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cls1ActionPerformed(evt);
            }
        });

        cls2.setText("class_2");
        cls2.setVisible(false);
        cls2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cls2ActionPerformed(evt);
            }
        });

        cls3.setText("class_3");
        cls3.setVisible(false);
        cls3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cls3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Your classes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(398, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cls1)
                                .addGap(151, 151, 151)
                                .addComponent(cls2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cls3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cls1)
                    .addComponent(cls2)
                    .addComponent(cls3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        setSize(new java.awt.Dimension(656, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            welcomeMsg.setText(String.format("Home, Welcome %s", this.u.rs.getString("first_name")));
            ResultSet classes = this.u.getCourses();
            int counter = 0;
            while(classes.next()) {
                this.classesData[counter] = new classData(this.c, classes.getString("classroom_id"));
                switch(counter) {
                    case 0:
                        cls1.setText(this.classesData[counter].rs.getString("name"));
                        cls1.setVisible(true);
                        break;
                    case 1:
                        cls2.setText(this.classesData[counter].rs.getString("name"));
                        cls2.setVisible(true);
                        break;
                    case 2:
                        cls3.setText(this.classesData[counter].rs.getString("name"));
                        cls3.setVisible(true);
                        break;
                }
                counter++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        class_creation cc = new class_creation(this.c, this.u);
        cc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cls1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cls1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        classroom cls = new classroom(this.c, this.u, this.classesData[0]);
        cls.setVisible(true);
    }//GEN-LAST:event_cls1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        join_class j = new join_class(this.c, this.u);
        j.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cls2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cls2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        classroom cls = new classroom(this.c, this.u, this.classesData[1]);
        cls.setVisible(true);
    }//GEN-LAST:event_cls2ActionPerformed

    private void cls3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cls3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        classroom cls = new classroom(this.c, this.u, this.classesData[2]);
        cls.setVisible(true);
    }//GEN-LAST:event_cls3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cls1;
    private javax.swing.JButton cls2;
    private javax.swing.JButton cls3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel welcomeMsg;
    // End of variables declaration//GEN-END:variables
}
